# Generated by Django 5.2.9 on 2026-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if republished elsewhere'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70),
        ),
        migrations.AddField(
            model_name='project',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='project_og/'),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='External OG image URL (1200x630 recommended)'),
        ),
        migrations.AddField(
            model_name='project',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=100),
        ),
    ]
