# Generated by Django 5.2.9 on 2026-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_images/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_org_logos/'),
        ),
        migrations.AddField(
            model_name='education',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='education_logos/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_authors/'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
