# Generated by Django 5.2.9 on 2025-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Achievement image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Featured image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Social sharing image as binary (1200x630)', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Certificate image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization_logo_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Organization logo as binary', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='logo_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Institution logo as binary', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(editable=True, help_text='Image stored as binary data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Profile image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Resume file as binary', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Featured image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_image_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Author image as binary', null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_logo_data',
            field=models.BinaryField(blank=True, editable=True, help_text='Company logo as binary', null=True),
        ),
    ]
