# Generated by Django 5.2.9 on 2026-01-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image_data',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='og_image_data',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_image_data',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='organization_logo_data',
        ),
        migrations.RemoveField(
            model_name='education',
            name='logo_data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured_image_data',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_image_data',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='company_logo_data',
        ),
        migrations.AddField(
            model_name='achievement',
            name='image_url',
            field=models.URLField(blank=True, help_text='External achievement image URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External featured image URL (CDN/S3/Cloudinary)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='External social sharing image URL (1200x630)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_image_url',
            field=models.URLField(blank=True, help_text='External certificate image URL'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization_logo_url',
            field=models.URLField(blank=True, help_text='External organization logo URL'),
        ),
        migrations.AddField(
            model_name='education',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External institution logo URL'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (CDN/S3/Cloudinary)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='External profile image URL (CDN/S3/Cloudinary)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.URLField(blank=True, help_text='External resume URL (PDF)'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External featured image URL (CDN/S3/Cloudinary)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_image_url',
            field=models.URLField(blank=True, help_text='External author image URL'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_logo_url',
            field=models.URLField(blank=True, help_text='External company logo URL'),
        ),
    ]
