# Generated by Django 5.2.9 on 2025-12-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_achievement_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this achievement on homepage'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this category on homepage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this blog post on homepage'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this tag on homepage'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this certificate on homepage'),
        ),
        migrations.AddField(
            model_name='education',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this education on homepage'),
        ),
        migrations.AddField(
            model_name='image',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this image on homepage gallery'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this project on homepage'),
        ),
        migrations.AddField(
            model_name='skill',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this skill on homepage'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Display this social link on homepage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this testimonial on homepage'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this work experience on homepage'),
        ),
    ]
