# Generated by Django 5.2.9 on 2026-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_achievement_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog_featured/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog_og/'),
        ),
    ]
