# Generated by Django 5.2.9 on 2026-01-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_achievement_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='api.profile'),
        ),
    ]
