# Generated by Django 5.2.9 on 2025-12-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_achievement_show_on_home_blogcategory_show_on_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Magic Portfolio', max_length=255)),
                ('site_description', models.TextField(default='A portfolio website')),
                ('base_url', models.URLField(default='https://demo.magic-portfolio.com')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='system', max_length=20)),
                ('neutral_color', models.CharField(choices=[('sand', 'Sand'), ('gray', 'Gray'), ('slate', 'Slate'), ('custom', 'Custom')], default='gray', max_length=20)),
                ('brand_color', models.CharField(choices=[('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('magenta', 'Magenta'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('moss', 'Moss'), ('green', 'Green'), ('emerald', 'Emerald'), ('aqua', 'Aqua'), ('cyan', 'Cyan'), ('custom', 'Custom')], default='cyan', max_length=20)),
                ('accent_color', models.CharField(choices=[('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('magenta', 'Magenta'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('moss', 'Moss'), ('green', 'Green'), ('emerald', 'Emerald'), ('aqua', 'Aqua'), ('cyan', 'Cyan'), ('custom', 'Custom')], default='red', max_length=20)),
                ('solid_style', models.CharField(choices=[('flat', 'Flat'), ('plastic', 'Plastic')], default='flat', max_length=20)),
                ('border_style', models.CharField(choices=[('rounded', 'Rounded'), ('playful', 'Playful'), ('conservative', 'Conservative')], default='playful', max_length=20)),
                ('surface_style', models.CharField(choices=[('filled', 'Filled'), ('translucent', 'Translucent')], default='translucent', max_length=20)),
                ('transition_style', models.CharField(choices=[('all', 'All'), ('micro', 'Micro'), ('macro', 'Macro')], default='all', max_length=20)),
                ('scaling', models.PositiveIntegerField(choices=[(90, '90%'), (95, '95%'), (100, '100%'), (105, '105%'), (110, '110%')], default=100)),
                ('display_location', models.BooleanField(default=True)),
                ('display_time', models.BooleanField(default=True)),
                ('display_theme_switcher', models.BooleanField(default=True)),
                ('mailchimp_action', models.URLField(blank=True, help_text='Mailchimp subscribe form action URL')),
                ('schema_type', models.CharField(choices=[('Organization', 'Organization'), ('Person', 'Person')], default='Organization', max_length=50)),
                ('schema_email', models.EmailField(blank=True, max_length=254)),
                ('threads_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('enable_social_sharing', models.BooleanField(default=True)),
                ('share_on_x', models.BooleanField(default=True)),
                ('share_on_linkedin', models.BooleanField(default=True)),
                ('share_on_facebook', models.BooleanField(default=False)),
                ('share_on_pinterest', models.BooleanField(default=False)),
                ('share_on_whatsapp', models.BooleanField(default=False)),
                ('share_on_reddit', models.BooleanField(default=False)),
                ('share_on_telegram', models.BooleanField(default=False)),
                ('share_email', models.BooleanField(default=True)),
                ('share_copy_link', models.BooleanField(default=True)),
                ('protected_routes', models.TextField(blank=True, help_text='JSON array of protected routes, e.g., ["/work/automate-design-handovers-with-a-figma-to-code-pipeline"]')),
                ('enable_route_home', models.BooleanField(default=True)),
                ('enable_route_about', models.BooleanField(default=True)),
                ('enable_route_work', models.BooleanField(default=True)),
                ('enable_route_blog', models.BooleanField(default=True)),
                ('enable_route_gallery', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name (leave blank for default)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('medium', 'Medium'), ('dev', 'Dev.to'), ('stackoverflow', 'Stack Overflow'), ('website', 'Personal Website'), ('discord', 'Discord'), ('threads', 'Threads'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], max_length=20),
        ),
    ]
