# Generated by Django 5.2.9 on 2025-12-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_siteconfiguration_alter_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='viz_style',
            field=models.CharField(choices=[('flat', 'Flat'), ('gradient', 'Gradient'), ('outline', 'Outline')], default='gradient', help_text='Visualization style for charts and data displays', max_length=20),
        ),
    ]
