# Generated by Django 5.2.9 on 2025-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_siteconfiguration_viz_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('language', 'Language'), ('frontend-dev', 'Frontend Development'), ('backend-dev', 'Backend Development'), ('mobile-app-dev', 'Mobile App Development'), ('ai-ml', 'AI/ML'), ('database', 'Database'), ('data-visualization', 'Data Visualization'), ('devops', 'DevOps'), ('baas', 'Backend Services (BaaS)'), ('frameworks', 'Frameworks'), ('testing', 'Testing'), ('softwares', 'Softwares'), ('static-site-generator', 'Static Site Generator'), ('game-engine', 'Game Engine'), ('automation', 'Automation'), ('others', 'Others')], default='language', max_length=25),
        ),
    ]
