# Generated by Django 5.2.9 on 2025-12-31 16:52

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    """
    Populate unique slugs for existing instances of models that need them.
    """
    models_to_update = {
        'Achievement': ('title',),
        'Certificate': ('title',),
        'Education': ('institution', 'degree'),
        'Skill': ('name',),
        'Testimonial': ('author_name', 'date'),
    }

    for model_name, fields in models_to_update.items():
        Model = apps.get_model('api', model_name)
        for instance in Model.objects.all():
            base_slug = slugify("-".join(str(getattr(instance, f)) for f in fields))
            slug = base_slug
            counter = 1
            while Model.objects.filter(slug=slug).exclude(pk=instance.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            instance.slug = slug
            instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_skill_skill_type'),
    ]

    operations = [
        # Step 1: Add slug fields, allowing them to be null temporarily
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        
        # Step 2: Populate slugs for existing data
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Alter fields to be unique and not nullable
        migrations.AlterField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
