
import {
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  Mail,
  Globe,
  User,
  Grid,
  BookOpen,
  Link,
  Calendar,
  Home,
  Image,
  Eye,
  EyeOff,
  FileText,
  Rocket,
  MoreHorizontal,
  Briefcase,
  GraduationCap,
  Award,
  Star,
  Zap,
  ChevronDown,
  Loader2,
  MapPin,
  ExternalLink,
  Download,
  Code,
  Terminal,
  Cpu,
  Menu,
  X,
  Check,
  AlertCircle
} from 'lucide-react';

// Brand icons from react-icons
import {
  FaGithub,
  FaLinkedin,
  FaXTwitter,
  FaInstagram,
  FaFacebook,
  FaYoutube,
  FaDribbble,
  FaBehance,
  FaMedium,
  FaDev,
  FaStackOverflow,
  FaDiscord,
  FaThreads,
  FaPinterest,
  FaReddit,
  FaTelegram,
  FaWhatsapp,
  FaPlay,
  FaImage,
  FaGlobe,
} from 'react-icons/fa6';
import { FaExternalLinkAlt } from 'react-icons/fa';

// Technology / Brand icons (Simple Icons)
import {
  SiC,
  SiCplusplus,
  SiCsharp,
  SiGo,
  SiJava,
  SiJavascript,
  SiTypescript,
  SiPhp,
  SiPerl,
  SiRuby,
  SiScala,
  SiPython,
  SiSwift,
  SiObjectivec,
  SiClojure,
  SiRust,
  SiHaskell,
  SiCoffeescript,
  SiElixir,
  SiErlang,
  SiNim,
  SiVuejs,
  SiReact,
  SiSvelte,
  SiAngular,
  SiBackbone,
  SiBootstrap,
  SiVuetify,
  SiCss3,
  SiHtml5,
  SiPug,
  SiGulp,
  SiSass,
  SiRedux,
  SiWebpack,
  SiBabel,
  SiTailwindcss,
  SiMaterialui,
  SiBulma,
  SiQt,
  SiNodedotjs,
  SiSpring,
  SiExpress,
  SiGraphql,
  SiApachekafka,
  SiSolr,
  SiRabbitmq,
  SiHadoop,
  SiNginx,
  SiNestjs,
  SiAndroid,
  SiFlutter,
  SiDart,
  SiKotlin,
  SiXamarin,
  SiIonic,
  SiApachecordova,
  SiTensorflow,
  SiPytorch,
  SiPandas,
  SiOpencv,
  SiScikitlearn,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiOracle,
  SiCassandra,
  SiCouchdb,
  SiApachehive,
  SiRealm,
  SiMariadb,
  SiCockroachdb,
  SiElasticsearch,
  SiSqlite,
  SiMicrosoftsqlserver,
  SiD3DotJs,
  SiChartdotjs,
  SiKibana,
  SiGrafana,
  SiAmazonaws,
  SiDocker,
  SiJenkins,
  SiGooglecloud,
  SiKubernetes,
  SiBash,
  SiMicrosoftazure,
  SiVagrant,
  SiCircleci,
  SiTravisci,
  SiFirebase,
  SiAppwrite,
  SiAmplify,
  SiHeroku,
  SiDjango,
  SiDotnet,
  SiElectron,
  SiSymfony,
  SiLaravel,
  SiCodeigniter,
  SiRubyonrails,
  SiFlask,
  SiQuasar,
  SiCypress,
  SiSelenium,
  SiJest,
  SiMocha,
  SiPuppeteer,
  SiKarma,
  SiJasmine,
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiXd,
  SiFigma,
  SiBlender,
  SiSketch,
  SiInvision,
  SiFramer,
  SiMathworks,
  SiNextdotjs,
  SiGatsby,
  SiHugo,
  SiJekyll,
  SiNuxtdotjs,
  SiEleventy,
  SiUnity,
  SiUnrealengine,
  SiZapier,
  SiIfttt,
  SiLinux,
  SiGit,
  SiArduino,
} from 'react-icons/si';

export const Icons = {
  // Navigation
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  menu: Menu,
  close: X,
  openLink: Link,
  externalLink: ExternalLink,
  download: Download,
  loader: Loader2,
  more: MoreHorizontal,
  
  // Core Sections
  home: Home,
  user: User,
  grid: Grid,
  blog: BookOpen,
  projects: Briefcase,
  experience: Briefcase,
  education: GraduationCap,
  awards: Award,
  certificates: Award,
  skills: Zap,
  testimonials: Star,
  contact: Mail,
  
  // Features
  gallery: FaImage,
  calendar: Calendar,
  document: FileText,
  rocket: Rocket,
  eye: Eye,
  eyeOff: EyeOff,
  mapPin: MapPin,
  code: Code,
  terminal: Terminal,
  cpu: Cpu,
  check: Check,
  alert: AlertCircle,
  play: FaPlay,

  // Technologies (skills)
  // Programming languages
  c: SiC,
  cplusplus: SiCplusplus,
  csharp: SiCsharp,
  go: SiGo,
  java: SiJava,
  javascript: SiJavascript,
  typescript: SiTypescript,
  php: SiPhp,
  perl: SiPerl,
  ruby: SiRuby,
  scala: SiScala,
  python: SiPython,
  swift: SiSwift,
  objectivec: SiObjectivec,
  clojure: SiClojure,
  rust: SiRust,
  haskell: SiHaskell,
  coffeescript: SiCoffeescript,
  elixir: SiElixir,
  erlang: SiErlang,
  nim: SiNim,

  // Frontend
  vuejs: SiVuejs,
  react: SiReact,
  svelte: SiSvelte,
  angularjs: SiAngular,
  angular: SiAngular,
  backbonejs: SiBackbone,
  bootstrap: SiBootstrap,
  vuetify: SiVuetify,
  css3: SiCss3,
  html5: SiHtml5,
  pug: SiPug,
  gulp: SiGulp,
  sass: SiSass,
  redux: SiRedux,
  webpack: SiWebpack,
  babel: SiBabel,
  tailwind: SiTailwindcss,
  materialize: SiMaterialui,
  bulma: SiBulma,
  gtk: SiQt, // fallback
  qt: SiQt,
  wx_widgets: SiQt, // fallback

  // Backend / APIs
  nodejs: SiNodedotjs,
  spring: SiSpring,
  express: SiExpress,
  graphql: SiGraphql,
  kafka: SiApachekafka,
  solr: SiSolr,
  rabbitmq: SiRabbitmq,
  hadoop: SiHadoop,
  nginx: SiNginx,
  openresty: SiNginx, // fallback
  nestjs: SiNestjs,

  // Mobile
  android: SiAndroid,
  flutter: SiFlutter,
  dart: SiDart,
  kotlin: SiKotlin,
  nativescript: SiNodedotjs, // fallback
  xamarin: SiXamarin,
  reactnative: SiReact,
  ionic: SiIonic,
  apachecordova: SiApachecordova,

  // AI / ML / Data
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  pandas: SiPandas,
  seaborn: SiPandas, // fallback
  opencv: SiOpencv,
  scikit_learn: SiScikitlearn,

  // Databases
  mongodb: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  redis: SiRedis,
  oracle: SiOracle,
  cassandra: SiCassandra,
  couchdb: SiCouchdb,
  hive: SiApachehive,
  realm: SiRealm,
  mariadb: SiMariadb,
  cockroachdb: SiCockroachdb,
  elasticsearch: SiElasticsearch,
  sqlite: SiSqlite,
  mssql: SiMicrosoftsqlserver,

  // Data Viz / Monitoring
  d3js: SiD3DotJs,
  chartjs: SiChartdotjs,
  canvasjs: SiChartdotjs, // fallback
  kibana: SiKibana,
  grafana: SiGrafana,

  // DevOps / Cloud
  aws: SiAmazonaws,
  docker: SiDocker,
  jenkins: SiJenkins,
  gcp: SiGooglecloud,
  kubernetes: SiKubernetes,
  bash: SiBash,
  azure: SiMicrosoftazure,
  vagrant: SiVagrant,
  circleci: SiCircleci,
  travisci: SiTravisci,

  // BaaS / Hosting
  firebase: SiFirebase,
  appwrite: SiAppwrite,
  amplify: SiAmplify,
  heroku: SiHeroku,

  // Frameworks / Backend frameworks
  django: SiDjango,
  dotnet: SiDotnet,
  electron: SiElectron,
  symfony: SiSymfony,
  laravel: SiLaravel,
  codeigniter: SiCodeigniter,
  rails: SiRubyonrails,
  flask: SiFlask,
  quasar: SiQuasar,

  // Testing
  cypress: SiCypress,
  selenium: SiSelenium,
  jest: SiJest,
  mocha: SiMocha,
  puppeteer: SiPuppeteer,
  karma: SiKarma,
  jasmine: SiJasmine,

  // Tools / Design / Others
  illustrator: SiAdobeillustrator,
  photoshop: SiAdobephotoshop,
  xd: SiXd,
  figma: SiFigma,
  blender: SiBlender,
  sketch: SiSketch,
  invision: SiInvision,
  framer: SiFramer,
  matlab: SiMathworks,

  // Static sites / SSGs
  nextjs: SiNextdotjs,
  gatsby: SiGatsby,
  hugo: SiHugo,
  jekyll: SiJekyll,
  nuxtjs: SiNuxtdotjs,
  _11ty: SiEleventy,

  // Game Engines
  unity: SiUnity,
  unreal: SiUnrealengine,

  // Automation
  zapier: SiZapier,
  ifttt: SiIfttt,

  // Misc
  linux: SiLinux,
  git: SiGit,
  arduino: SiArduino,

  // Fallbacks
  globe: FaGlobe,
  external: FaExternalLinkAlt,
  email: Mail,
  link: Link
};

export const SocialIcons: Record<string, any> = {
  linkedin: FaLinkedin,
  github: FaGithub,
  twitter: FaXTwitter,
  x: FaXTwitter,
  instagram: FaInstagram,
  facebook: FaFacebook,
  youtube: FaYoutube,
  dribbble: FaDribbble,
  behance: FaBehance,
  medium: FaMedium,
  dev: FaDev,
  stackoverflow: FaStackOverflow,
  discord: FaDiscord,
  threads: FaThreads,
  pinterest: FaPinterest,
  reddit: FaReddit,
  telegram: FaTelegram,
  whatsapp: FaWhatsapp,
  email: Mail,
  website: Globe,
  other: Link
};

export type IconName = keyof typeof Icons;
