import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineEllipsisHorizontalCircle,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

// Additional icons from lucide-react (small, consistent icon set)
import {
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  Mail,
  Globe as LucideGlobe,
  User as LucideUser,
  Grid as LucideGrid,
  BookOpen,
  Link as LucideLink,
  Calendar as LucideCalendar,
  Home as LucideHome,
  Image as LucideImage,
  Eye as LucideEye,
  EyeOff as LucideEyeOff,
  FileText,
  Rocket as LucideRocket,
  MoreHorizontal,
  Briefcase,
  GraduationCap,
  Award,
  Star,
  Zap,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Loader2,
  MapPin,
  Phone,
  Search,
  Info,
  AlertTriangle,
  ExternalLink,
  Download,
  Code,
  Terminal,
  Cpu,
  Menu,
  X as LucideX,
  Check,
  AlertCircle,
} from 'lucide-react';

// A few extra brand/utility icons from FontAwesome not already imported
import { FaExternalLinkAlt } from 'react-icons/fa';
import { FaPlay, FaImage, FaGlobe, FaJava, FaMicrosoft, FaAws } from 'react-icons/fa6';

import {
  SiAndroid,
  SiArduino,
  SiBootstrap,
  SiC,
  SiCplusplus,
  SiCss3,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGraphql,
  SiHtml5,
  SiJava,
  SiJavascript,
  SiKotlin,
  SiLinux,
  SiMongodb,
  SiNginx,
  SiNodedotjs,
  SiOpencv,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiPytorch,
  SiReact,
  SiRedis,
  SiSqlite,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiFigma,
  SiNextdotjs,
  SiSupabase,
  SiAdobephotoshop,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaInstagram, FaYoutube, FaDribbble, FaBehance, FaMedium, FaDev, FaStackOverflow, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  apps: PiGridFourDuotone, // alias for header MegaMenu toggle
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  youtube: FaYoutube,
  dribbble: FaDribbble,
  behance: FaBehance,
  medium: FaMedium,
  dev: FaDev,
  stackoverflow: FaStackOverflow,

  /* Added icons (non-destructive) */
  arrowLeft: ArrowLeft,
  mail: Mail,
  bookOpen: BookOpen,
  externalLink: ExternalLink,
  download: Download,
  loader: Loader2,
  more: MoreHorizontal,
  briefcase: Briefcase,
  graduationCap: GraduationCap,
  award: Award,
  star: Star,
  zap: Zap,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  mapPin: MapPin,
  phone: Phone,
  search: Search,
  info: Info,
  warning: AlertTriangle,
  code: Code,
  terminal: Terminal,
  cpu: Cpu,
  menu: Menu,
  close: LucideX,
  check: Check,
  checkCircle: Check,
  alert: AlertCircle,
  play: FaPlay,
  image: FaImage,
  /* Skill / brand icons from DB */
  android: SiAndroid,
  arduino: SiArduino,
  aws: FaAws,
  bootstrap: SiBootstrap,
  c: SiC,
  cplusplus: SiCplusplus,
  css3: SiCss3,
  django: SiDjango,
  docker: SiDocker,
  express: SiExpress,
  firebase: SiFirebase,
  flask: SiFlask,
  flutter: SiFlutter,
  git: SiGit,
  graphql: SiGraphql,
  html5: SiHtml5,
  java: SiJava,
  kotlin: SiKotlin,
  linux: SiLinux,
  mongodb: SiMongodb,
  nginx: SiNginx,
  nodejs: SiNodedotjs,
  opencv: SiOpencv,
  pandas: SiPandas,
  photoshop: SiAdobephotoshop,
  postgresql: SiPostgresql,
  postman: SiPostman,
  python: SiPython,
  pytorch: SiPytorch,
  react: SiReact,
  redis: SiRedis,
  sqlite: SiSqlite,
  tailwind: SiTailwindcss,
  tensorflow: SiTensorflow,
  typescript: SiTypescript,

  /* Section-focused icons */
  projects: Briefcase,
  experience: Briefcase,
  education: GraduationCap,
  awards: Award,
  certificates: Award,
  skills: Zap,
  testimonials: Star,
  contact: Mail,

  /* Keep existing fallbacks */
  website: HiOutlineGlobeAsiaAustralia,
  other: HiOutlineEllipsisHorizontalCircle,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
